# Introduction

<div class="alert alert-block alert-warning">
<font color=black>

**What?** `numpy.reshape()` method

</font>
</div>

# Motivation

<div class="alert alert-block alert-info">
<font color=black>

- While working with tensor and in particular while working with RNNs and LSTMs model one of the most used method is `reshape`.
- Hence it is paramount to understand how it works.

</font>
</div>

# Generate some data

In [2]:
import numpy as np
# 10 rows and 2 columns
a = np.zeros((10, 2))

In [3]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
a.shape

(10, 2)

In [36]:
# Each of the 10 entry has a matrix of 4x4
b = np.random.random((10, 4, 4))

In [37]:
b

array([[[0.95482315, 0.30029369, 0.910335  , 0.08020976],
        [0.26087665, 0.74355695, 0.87701158, 0.91257291],
        [0.13802438, 0.72547967, 0.45585291, 0.93402801],
        [0.64295938, 0.3969412 , 0.80509458, 0.83883464]],

       [[0.03851085, 0.32370843, 0.0220204 , 0.38591885],
        [0.75635069, 0.20453466, 0.30989943, 0.47281816],
        [0.98911688, 0.59242044, 0.04897852, 0.03649281],
        [0.37933071, 0.84537176, 0.62905873, 0.31277875]],

       [[0.89156262, 0.15544464, 0.26935212, 0.80400922],
        [0.77176994, 0.50414123, 0.83006502, 0.13350817],
        [0.27842473, 0.83442042, 0.33978894, 0.21968792],
        [0.47431632, 0.90194498, 0.06735531, 0.12865442]],

       [[0.66708111, 0.76313565, 0.23238454, 0.54116513],
        [0.68602646, 0.63017342, 0.53805824, 0.92148395],
        [0.84880985, 0.10472642, 0.50774023, 0.78848237],
        [0.8537111 , 0.65784864, 0.07181228, 0.42720509]],

       [[0.97088601, 0.01786599, 0.02684165, 0.16144545],
      

In [44]:
b.shape

(10, 4, 4)

# -1 behviour

<div class="alert alert-block alert-info">
<font color=black>

- It simply means that it is an unknown dimension and we want numpy to figure it out. 
- If we say `a.reshape(-1,1)` we are saying we'd like to have a new array with 1 column and we are asking numpy to figure it out what the the number of rows will be.
- One one shape can be inferred.
- **How does numpy inferred the shape?** `inferred shape = length of flattened array / the sum of given shapes.`
- This means that something like this `a.reshape(-1,-1)` is **NOT** allowed.

</font>
</div>

In [4]:
a.reshape(-1,1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [ ]:
# This is an alternative syntax, totally equivalent but a bit more long
np.reshape(a, (-1,1))

In [9]:
a.reshape(-1,1).shape

(20, 1)

In [14]:
# Just checking the shape. ndarray are n-dimensional array
type(a.reshape(-1,1))

numpy.ndarray

In [11]:
# This is not allowed!
a.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [8]:
a.reshape(-1,)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [12]:
a.reshape(-1,).shape

(20,)

In [13]:
# Just checking the type
type(a.reshape(-1,))

numpy.ndarray

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

# Multidimensional array = tensor

In [38]:
b.shape

(10, 4, 4)

In [40]:
b

array([[[0.95482315, 0.30029369, 0.910335  , 0.08020976],
        [0.26087665, 0.74355695, 0.87701158, 0.91257291],
        [0.13802438, 0.72547967, 0.45585291, 0.93402801],
        [0.64295938, 0.3969412 , 0.80509458, 0.83883464]],

       [[0.03851085, 0.32370843, 0.0220204 , 0.38591885],
        [0.75635069, 0.20453466, 0.30989943, 0.47281816],
        [0.98911688, 0.59242044, 0.04897852, 0.03649281],
        [0.37933071, 0.84537176, 0.62905873, 0.31277875]],

       [[0.89156262, 0.15544464, 0.26935212, 0.80400922],
        [0.77176994, 0.50414123, 0.83006502, 0.13350817],
        [0.27842473, 0.83442042, 0.33978894, 0.21968792],
        [0.47431632, 0.90194498, 0.06735531, 0.12865442]],

       [[0.66708111, 0.76313565, 0.23238454, 0.54116513],
        [0.68602646, 0.63017342, 0.53805824, 0.92148395],
        [0.84880985, 0.10472642, 0.50774023, 0.78848237],
        [0.8537111 , 0.65784864, 0.07181228, 0.42720509]],

       [[0.97088601, 0.01786599, 0.02684165, 0.16144545],
      

In [39]:
# Here we want array with only one column. 
# The number of rows will be 10*4*4 = 160
b.reshape(-1,1)

array([[0.95482315],
       [0.30029369],
       [0.910335  ],
       [0.08020976],
       [0.26087665],
       [0.74355695],
       [0.87701158],
       [0.91257291],
       [0.13802438],
       [0.72547967],
       [0.45585291],
       [0.93402801],
       [0.64295938],
       [0.3969412 ],
       [0.80509458],
       [0.83883464],
       [0.03851085],
       [0.32370843],
       [0.0220204 ],
       [0.38591885],
       [0.75635069],
       [0.20453466],
       [0.30989943],
       [0.47281816],
       [0.98911688],
       [0.59242044],
       [0.04897852],
       [0.03649281],
       [0.37933071],
       [0.84537176],
       [0.62905873],
       [0.31277875],
       [0.89156262],
       [0.15544464],
       [0.26935212],
       [0.80400922],
       [0.77176994],
       [0.50414123],
       [0.83006502],
       [0.13350817],
       [0.27842473],
       [0.83442042],
       [0.33978894],
       [0.21968792],
       [0.47431632],
       [0.90194498],
       [0.06735531],
       [0.128

In [41]:
# As you can see the number of rows are as we predicted them
b.reshape(-1,1).shape

(160, 1)

In [42]:
# Here we say we'd like to have each entrued organised by 2x2 matrices
# The number of entries is inferred by reshape method
b.reshape(-1,2,2)

array([[[0.95482315, 0.30029369],
        [0.910335  , 0.08020976]],

       [[0.26087665, 0.74355695],
        [0.87701158, 0.91257291]],

       [[0.13802438, 0.72547967],
        [0.45585291, 0.93402801]],

       [[0.64295938, 0.3969412 ],
        [0.80509458, 0.83883464]],

       [[0.03851085, 0.32370843],
        [0.0220204 , 0.38591885]],

       [[0.75635069, 0.20453466],
        [0.30989943, 0.47281816]],

       [[0.98911688, 0.59242044],
        [0.04897852, 0.03649281]],

       [[0.37933071, 0.84537176],
        [0.62905873, 0.31277875]],

       [[0.89156262, 0.15544464],
        [0.26935212, 0.80400922]],

       [[0.77176994, 0.50414123],
        [0.83006502, 0.13350817]],

       [[0.27842473, 0.83442042],
        [0.33978894, 0.21968792]],

       [[0.47431632, 0.90194498],
        [0.06735531, 0.12865442]],

       [[0.66708111, 0.76313565],
        [0.23238454, 0.54116513]],

       [[0.68602646, 0.63017342],
        [0.53805824, 0.92148395]],

       [[0.84880985,

In [43]:
b.reshape(-1,2,2).shape

(40, 2, 2)

In [49]:
# You can compare the first row the the unchange array
print(b[0])
# with the first rwo of the reshaped array to see how they were organised
print(b.reshape(-1,2,2)[:4])

[[0.95482315 0.30029369 0.910335   0.08020976]
 [0.26087665 0.74355695 0.87701158 0.91257291]
 [0.13802438 0.72547967 0.45585291 0.93402801]
 [0.64295938 0.3969412  0.80509458 0.83883464]]
[[[0.95482315 0.30029369]
  [0.910335   0.08020976]]

 [[0.26087665 0.74355695]
  [0.87701158 0.91257291]]

 [[0.13802438 0.72547967]
  [0.45585291 0.93402801]]

 [[0.64295938 0.3969412 ]
  [0.80509458 0.83883464]]]


# References

<div class="alert alert-block alert-warning">
<font color=black>

- https://numpy.org/doc/stable/reference/generated/numpy.reshape.html
- https://stackoverflow.com/questions/18691084/what-does-1-mean-in-numpy-reshape
- https://www.mikulskibartosz.name/numpy-reshape-explained/

</font>
</div>

# Conclusions

<div class="alert alert-danger">
<font color=black>

- The number of elements in the final array is same as that of the initial array or data frame.
- Input `-1` allows for the user laziness thus numpy will figure it our based on what you provide as input: No of rows or columns.

</font>
</div>