<h1>Table of Contents<span class="tocSkip"></span></h1>


# Introduction
<hr style="border:2px solid black"> </hr>


**What?** `numpy.pad()` method



# Motivation
<hr style="border:2px solid black"> </hr>


- `np.pad` is used to artificially change the shappe of a matrix.
- An image can be represented via matrix or a tensor more precisely.
- Padding describes the addition of zeros to the *border of matrix*.
- Say you have an image of dimension `(28,28,1)` and you'd like to turn it into a `(32,32,1)`, you can do it by adding zeros all around it.



In [2]:
import numpy as np

# Example #1
<hr style="border:2px solid black"> </hr>

In [5]:
# Create a tensor
z = np.arange(12).reshape(3,2,2)
print(z.shape)
print(z)

(3, 2, 2)
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]



- The pad_width argument to np.pad works like this: ((axis 1 pad before, axis 1 pad after), ...)
- So if you want to pad 1 pixel on each side you should do ((0,0), (1,1), (1,1)). 



In [7]:
z = np.pad(z, ((0,0),(1,1),(1,1)), 'constant')
print(z.shape)
# (3, 4, 4)
print(z)

(3, 6, 6)
[[[ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]
  [ 0  0  0  1  0  0]
  [ 0  0  2  3  0  0]
  [ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]
  [ 0  0  4  5  0  0]
  [ 0  0  6  7  0  0]
  [ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]]

 [[ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]
  [ 0  0  8  9  0  0]
  [ 0  0 10 11  0  0]
  [ 0  0  0  0  0  0]
  [ 0  0  0  0  0  0]]]


In [8]:
# as an example, take a look at the second "image"
print(z[1])

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 4 5 0 0]
 [0 0 6 7 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


# References
<hr style="border:2px solid black"> </hr>


- https://stackoverflow.com/questions/61309432/padding-mnist-images-from-28-28-1-to-32-32-1
    
